# Generated by Django 5.2.5 on 2025-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('applications_count', models.IntegerField(default=0)),
                ('interviews_count', models.IntegerField(default=0)),
                ('offers_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Analytics Data',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_this_month', models.IntegerField(default=0)),
                ('interview_rate', models.FloatField(default=0)),
                ('offer_rate', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Stats',
            },
        ),
    ]
