# Generated by Django 5.2.5 on 2025-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_posting_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=50),
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
    ]
