# Generated by Django 5.2.5 on 2025-08-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_cover_letter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
