# Generated by Django 5.2.5 on 2025-08-11 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_timelineevent_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
