# Generated by Django 5.2.5 on 2025-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_timelineevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_uid',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
