# Generated by Django 5.2.5 on 2025-08-24 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_jobfilter_job_fetched_at_job_salary_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
