# Generated by Django 5.2.5 on 2025-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user_uid', 'job_posting_url'), name='unique_user_application'),
        ),
    ]
