# Generated by Django 5.2.5 on 2025-08-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_unique_user_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255, unique=True)),
                ('gmail_connected', models.BooleanField(default=False)),
                ('gmail_refresh_token', models.TextField(blank=True, null=True)),
                ('gmail_access_token', models.TextField(blank=True, null=True)),
                ('gmail_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_update_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.IntegerField(default=80)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('last_email_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='company_email_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='email_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='last_email_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('note', 'Note'), ('other', 'Other'), ('status_change', 'Status Change'), ('email_received', 'Email Received')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('received_date', models.DateTimeField()),
                ('classification', models.CharField(blank=True, choices=[('REJECTION', 'Rejection'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('FOLLOW_UP', 'Follow Up'), ('APPLICATION_RECEIVED', 'Application Received'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('suggested_status', models.CharField(blank=True, choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=20, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('status_updated', models.BooleanField(default=False)),
                ('timeline_created', models.BooleanField(default=False)),
                ('user_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='applications.application')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='email_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.emaillog'),
        ),
    ]
