# Generated by Django 5.2.5 on 2025-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_useremailsettings_application_company_email_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailsettings',
            name='email_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
