# Generated by Django 5.2.5 on 2025-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_useremailsettings_email_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailsettings',
            name='auto_process_emails',
            field=models.BooleanField(default=False),
        ),
    ]
