# Generated by Django 5.2.5 on 2025-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_useremailsettings_auto_process_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailsettings',
            name='last_email_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
