# Generated by Django 5.2.5 on 2025-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_useremailsettings_last_email_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailsettings',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
