# Generated by Django 5.2.5 on 2025-08-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_useremailsettings_processed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailsettings',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
