# Generated by Django 5.2.5 on 2025-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_remove_useremailsettings_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
